model: "ARCroco3DStereo(ARCroco3DStereoConfig(freeze='none', state_size=768, state_pe='2d', pos_embed='RoPE100', rgb_head=True, pose_head=True, patch_embed_cls='ManyAR_PatchEmbed', img_size=(512, 512), head_type='dpt', output_mode='pts3d+pose', depth_mode=('exp', -inf, inf), conf_mode=('exp', 1, inf), pose_mode=('exp', -inf, inf), enc_embed_dim=1024, enc_depth=24, enc_num_heads=16, dec_embed_dim=768, dec_depth=12, dec_num_heads=12, landscape_only=False))"
pretrained: null
load_only_encoder: False
long_context: False
fixed_length: True
resume: null
benchmark: False
num_views : 2
num_test_views : 4
n_corres_train: 0
n_corres_test: 0

train_criterion: ConfLoss(Regr3DPoseBatchList(L21, norm_mode='?avg_dis'), alpha=0.2) + RGBLoss(MSE)
test_criterion: Regr3DPose(L21, norm_mode='?avg_dis', gt_scale=True, sky_loss_value=0) + Regr3DPose_ScaleInv(L21, norm_mode='?avg_dis', gt_scale=True, sky_loss_value=0) + RGBLoss(L21)

resolution: [[512, 512]]

allow_repeat: True
dataset1: 'DL3DV_Multi(allow_repeat=${allow_repeat}, split="train", ROOT="/media/bora/Extreme Pro/ECCV_2026_SSD/DA3_WITH_CUT3R/robomimic_gt/dl3dv_multi", aug_crop=0, resolution=${resolution}, transform=ImgNorm, num_views=${num_views}, n_corres=${n_corres_train})'

train_dataset: 118 @ ${dataset1}
test_dataset: 20 @ ${dataset1}

seed: 0
batch_size: 1
accum_iter: 1
gradient_checkpointing: True
epochs: 100
start_epoch: 0
weight_decay: 0.05
lr: 1e-4
min_lr: 1e-6
warmup_epochs: 0
amp: 1

num_workers: 4
world_size: 1
local-rank: -1
dist_url: 'env://'
rank: 0
gpu: 0
distributed: False
dist_backend: 'nccl'

eval_freq: 0
save_freq: 1
keep_freq: 0
print_freq: 10
print_img_freq: 50000000
num_imgs_vis: 4
save_dir: '/media/bora/Extreme Pro/ECCV_2026_SSD/DA3_WITH_CUT3R/training/checkpoints'
exp_name: 'overfit_single_scene_v1'
task: 'cut3r'
logdir: ${save_dir}/${exp_name}/logs
output_dir: ${save_dir}/${exp_name}/
hydra:
  verbose: True
  run:
    dir: ${save_dir}/${exp_name}